### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by GhazanfarMir** [ahinkle/vscode-laravel-model-snippets#3]
First of all thanks for the repo and sorry for wrong approach to contact you. 
What font/theme are you using in the GIF?

**Comment by ahinkle** [comment]
Howdy @GhazanfarMir,

Glad to hear you like the extension.
Font: Operator Mono
Theme: [OperatorMonoDarkTheme](https://marketplace.visualstudio.com/items?itemName=Valiantsin.operatormonodarktheme)

**Comment by GhazanfarMir** [comment]
Thanks buddy.
